[package]
name = "musicbrainz"
version = "0.1.0"
authors = ["Leo Schwarz <mail@leoschwarz.com>"]
license = "Apache-2.0"
repository = "https://github.com/leoschwarz/musicbrainz_rust"

[features]
default = []

# Diesel integration implements diesel::AsExpression for Mbid.
diesel-integration = ["diesel"]

[dependencies]
diesel = { version = "0.12.1", optional = true }
error-chain = "0.10.0"
hyper = "0.10.9"
hyper-native-tls = "0.2.2"
url = "1.4.0"
uuid = { version = "0.5.0", features = ["use_std"] }
xpath_reader = "0.2.0"

[dev-dependencies]
yup-hyper-mock = "2.0.0"

